name: SLZB-06Mg24 Zigbee
device: EFR32MG24A020F1024IM40
base_project: src/zigbee_ncp
filename: "{manifest_name}_{ezsp_version}_{fw_variant}"
sdk: "gecko_sdk:4.5.0"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: zigbee_ncp
  ezsp_version: dynamic
  baudrate: 460800
  fw_variant: sw_flow

sdk_extension:
  - id: xncp
    version: 1.0.0
  - id: xncp_common
    version: 1.0.0

add_components:
- id: xncp_core
  from: xncp
- id: xncp_common_commands
  from: xncp_common

#slcp_defines:
#  SL_ZIGBEE_MULTICAST_TABLE_SIZE: 26
#  SL_ZIGBEE_ROUTE_TABLE_SIZE: 16
#  SL_ZIGBEE_DISCOVERY_TABLE_SIZE: 8
#slcp_defines:
#  EMBER_MAX_DEPTH: 5
#slcp_defines:
#  EMBER_BROADCAST_TABLE_TIMEOUT_QS: (2 * 4)

c_defines:
  #XNCP_MFG_MANUF_NAME: '"Nabu Casa"'
  #XNCP_MFG_BOARD_NAME: '"Home Assistant Connect ZBT-2"'
  #XNCP_BUILD_STRING: template:"{now:%Y%m%d%H%M%S}"
  XNCP_MFG_MANUF_NAME: '"Chris"'
  XNCP_MFG_BOARD_NAME: '"SLZB-MR3 Mg24"'
  XNCP_BUILD_STRING: template:"{now:%Y%m%d%H%M%S}"
  XNCP_MANUAL_SOURCE_ROUTE_TABLE_SIZE: 1

  EMBER_APS_UNICAST_MESSAGE_COUNT: 32
  EMBER_BINDING_TABLE_SIZE: 32
  EMBER_BROADCAST_TABLE_SIZE: 64
  EMBER_KEY_TABLE_SIZE: 12
  EMBER_MAX_END_DEVICE_CHILDREN: 32
  EMBER_PACKET_BUFFER_COUNT: 255
  EMBER_SOURCE_ROUTE_TABLE_SIZE: 0
  #EMBER_MAX_HOPS: 10
  #EMBER_MAX_DEPTH: 5
  EMBER_NEIGHBOR_TABLE_SIZE: 16


  EMBER_CHILD_TABLE_SIZE:
    type: c_flag
    value: 32

  EMBER_ROUTE_TABLE_SIZE:
    type: c_flag
    value: 250

  SL_IOSTREAM_USART_VCOM_BAUDRATE: 460800
  SL_IOSTREAM_USART_VCOM_RX_BUFFER_SIZE: 512
  SL_IOSTREAM_USART_VCOM_FLOW_CONTROL_TYPE: usartHwFlowControlCtsAndRts
  SL_IOSTREAM_USART_VCOM_PERIPHERAL: USART0
  SL_IOSTREAM_USART_VCOM_PERIPHERAL_NO: 0

  SL_IOSTREAM_USART_VCOM_TX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_TX_PIN:  5

  SL_IOSTREAM_USART_VCOM_RX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_RX_PIN:  6

  SL_IOSTREAM_USART_VCOM_CTS_PORT: 0
  SL_IOSTREAM_USART_VCOM_CTS_PIN:  0

  SL_IOSTREAM_USART_VCOM_RTS_PORT: 0
  SL_IOSTREAM_USART_VCOM_RTS_PIN:  0

